name: Deploy Application to Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ssh.euitsols.com
          username: u492-tb7rpjm3nxkw
          key: 

          port: 18765
          passphrase: 12qwaszx!@QW##$$
          script: |
            cd www/restaurant.euitsols.com/public_html
            git fetch --all
            git reset --hard origin/main
            git pull
